background = rgba(050623ff)
base = rgba(161151f2)
text = rgba(f2ecffff)
alternate_base = rgba(6d8cff55)
bright_text = rgba(f2ecffff)
accent = rgba(62d8ffff)
accent_secondary = rgba(e56bffff)

h1_size = 20
h2_size = 16
h3_size = 13
font_size = 12
small_font_size = 10
font_family = Pretendard
font_family_monospace = Jetendard
icon_theme = Papirus-Dark
rounding_large = 16
rounding_small = 8
