background = rgba(070b2aff)
base = rgba(111447f2)
text = rgba(e9e8ffff)
alternate_base = rgba(8b5cff55)
bright_text = rgba(e9e8ffff)
accent = rgba(33d6ffff)
accent_secondary = rgba(ff3cc7ff)

h1_size = 20
h2_size = 16
h3_size = 13
font_size = 12
small_font_size = 10
font_family = Pretendard
font_family_monospace = Jetendard
icon_theme = Papirus
rounding_large = 16
rounding_small = 8
