splash = false
ipc = true

wallpaper {
    monitor = eDP-1
    path = /home/kentakang/.local/share/backgrounds/cyberpunk-library-16x10.jpg
    fit_mode = cover
}

wallpaper {
    monitor =
    path = /home/kentakang/.local/share/backgrounds/cyberpunk-library-16x9.jpg
    fit_mode = cover
}
